services:
  postgres:
    image: postgres:15
    container_name: rehabfit-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rehabfit-backend:
    build: .
    container_name: rehabfit-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      embedding-service:
        condition: service_started
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://rehabfit-postgres:5432/${POSTGRES_DB}
        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        PINECONE_API_KEY: ${PINECONE_API_KEY}
        PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
        PINECONE_INDEX: ${PINECONE_INDEX}
        PINECONE_PROJECT: ${PINECONE_PROJECT}
        YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: ["java", "-jar", "target/rehabfit-0.0.1-SNAPSHOT.jar"]

  embedding-service:
    build:
      context: ../../../rehabfit-embedding-service
    container_name: rehabfit-embedding
    ports:
      - "5005:5005"

  pgadmin:
    image: dpage/pgadmin4
    container_name: rehabfit-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rehabfit.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data: